-- Commerce ERP (Postgres) — aligned with the SQLite version and the existing schema.rs.

CREATE TABLE IF NOT EXISTS commerce_units (id UUID PRIMARY KEY, name TEXT NOT NULL, symbol TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_warehouses (id UUID PRIMARY KEY, name TEXT NOT NULL, location TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_suppliers (id UUID PRIMARY KEY, name TEXT NOT NULL, contact_email TEXT, contact_phone TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_products (id UUID PRIMARY KEY, sku TEXT NOT NULL UNIQUE, name TEXT NOT NULL, description TEXT, unit_id UUID REFERENCES commerce_units(id), product_type TEXT NOT NULL DEFAULT 'goods', is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_procurement_requests (id UUID PRIMARY KEY, request_number TEXT NOT NULL UNIQUE, requested_by UUID, status TEXT NOT NULL DEFAULT 'DRAFT', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_procurement_lines (id UUID PRIMARY KEY, procurement_id UUID NOT NULL REFERENCES commerce_procurement_requests(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES commerce_products(id), quantity NUMERIC NOT NULL DEFAULT 1, notes TEXT);
CREATE TABLE IF NOT EXISTS commerce_purchase_orders (id UUID PRIMARY KEY, po_number TEXT NOT NULL UNIQUE, supplier_id UUID REFERENCES commerce_suppliers(id), status TEXT NOT NULL DEFAULT 'DRAFT', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_purchase_order_lines (id UUID PRIMARY KEY, purchase_order_id UUID NOT NULL REFERENCES commerce_purchase_orders(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES commerce_products(id), quantity NUMERIC NOT NULL, unit_price NUMERIC NOT NULL, notes TEXT);
CREATE TABLE IF NOT EXISTS commerce_goods_receipts (id UUID PRIMARY KEY, receipt_number TEXT NOT NULL UNIQUE, purchase_order_id UUID REFERENCES commerce_purchase_orders(id), warehouse_id UUID REFERENCES commerce_warehouses(id), received_at TIMESTAMPTZ NOT NULL DEFAULT now(), notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_goods_receipt_lines (id UUID PRIMARY KEY, receipt_id UUID NOT NULL REFERENCES commerce_goods_receipts(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES commerce_products(id), quantity NUMERIC NOT NULL, notes TEXT);
CREATE TABLE IF NOT EXISTS commerce_inventory_transactions (id UUID PRIMARY KEY, product_id UUID NOT NULL REFERENCES commerce_products(id), warehouse_id UUID NOT NULL REFERENCES commerce_warehouses(id), transaction_type TEXT NOT NULL, quantity NUMERIC NOT NULL, reference_type TEXT, reference_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS inv_tx_product_warehouse_idx ON commerce_inventory_transactions(product_id, warehouse_id);
CREATE TABLE IF NOT EXISTS commerce_sales_orders (id UUID PRIMARY KEY, so_number TEXT NOT NULL UNIQUE, customer_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'DRAFT', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_sales_lines (id UUID PRIMARY KEY, sales_order_id UUID NOT NULL REFERENCES commerce_sales_orders(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES commerce_products(id), quantity NUMERIC NOT NULL, unit_price NUMERIC NOT NULL, notes TEXT);
CREATE TABLE IF NOT EXISTS commerce_shipments (id UUID PRIMARY KEY, sales_order_id UUID NOT NULL REFERENCES commerce_sales_orders(id) ON DELETE CASCADE, warehouse_id UUID REFERENCES commerce_warehouses(id), shipped_at TIMESTAMPTZ NOT NULL DEFAULT now(), notes TEXT);
CREATE TABLE IF NOT EXISTS commerce_assets (id UUID PRIMARY KEY, asset_number TEXT NOT NULL UNIQUE, product_id UUID REFERENCES commerce_products(id), name TEXT NOT NULL, acquisition_cost NUMERIC NOT NULL, acquisition_date DATE NOT NULL, status TEXT NOT NULL DEFAULT 'active', location_id UUID REFERENCES commerce_warehouses(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS commerce_expenses (id UUID PRIMARY KEY, expense_number TEXT NOT NULL UNIQUE, category TEXT NOT NULL, description TEXT NOT NULL, amount NUMERIC NOT NULL, expense_date DATE NOT NULL, status TEXT NOT NULL DEFAULT 'DRAFT', approved_by UUID, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO gateway.permissions (module, action, description) VALUES ('commerce','read','View commerce'),('commerce','write','Manage commerce'),('commerce','admin','Admin commerce') ON CONFLICT (module, action) DO NOTHING;