-- CRM (Postgres) — aligned with the SQLite version and the existing schema.rs.

CREATE TABLE IF NOT EXISTS crm_leads (id UUID PRIMARY KEY, lead_number TEXT NOT NULL UNIQUE, company_name TEXT, contact_name TEXT NOT NULL, email TEXT, phone TEXT, source TEXT, status TEXT NOT NULL DEFAULT 'NEW', assigned_to UUID, product_id UUID REFERENCES commerce_products(id), estimated_value NUMERIC, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_opportunities (id UUID PRIMARY KEY, opp_number TEXT NOT NULL UNIQUE, lead_id UUID REFERENCES crm_leads(id), customer_id UUID, stage TEXT NOT NULL DEFAULT 'PROSPECT', probability NUMERIC DEFAULT 0.3, amount NUMERIC, expected_close DATE, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_customers (id UUID PRIMARY KEY, customer_number TEXT NOT NULL UNIQUE, name TEXT NOT NULL, email TEXT, phone TEXT, address TEXT, lead_id UUID REFERENCES crm_leads(id), opportunity_id UUID REFERENCES crm_opportunities(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_contacts (id UUID PRIMARY KEY, customer_id UUID NOT NULL REFERENCES crm_customers(id) ON DELETE CASCADE, name TEXT NOT NULL, email TEXT, role TEXT, phone TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_activities (id UUID PRIMARY KEY, related_type TEXT NOT NULL, related_id UUID NOT NULL, activity_type TEXT NOT NULL, subject TEXT NOT NULL, due_at TIMESTAMPTZ, done BOOLEAN NOT NULL DEFAULT false, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_quotes (id UUID PRIMARY KEY, quote_number TEXT NOT NULL UNIQUE, customer_id UUID REFERENCES crm_customers(id), opportunity_id UUID REFERENCES crm_opportunities(id), status TEXT NOT NULL DEFAULT 'DRAFT', valid_until DATE, total NUMERIC DEFAULT 0, sales_order_id UUID REFERENCES commerce_sales_orders(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_quote_lines (id UUID PRIMARY KEY, quote_id UUID NOT NULL REFERENCES crm_quotes(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES commerce_products(id), quantity NUMERIC NOT NULL, unit_price NUMERIC NOT NULL, notes TEXT);
CREATE TABLE IF NOT EXISTS accounting_invoices (id UUID PRIMARY KEY, invoice_number TEXT NOT NULL UNIQUE, sales_order_id UUID REFERENCES commerce_sales_orders(id), quote_id UUID REFERENCES crm_quotes(id), total NUMERIC NOT NULL, status TEXT NOT NULL DEFAULT 'DRAFT', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO gateway.permissions (module, action, description) VALUES ('crm','read','View CRM'),('crm','write','Manage CRM'),('crm','admin','Admin CRM') ON CONFLICT (module, action) DO NOTHING;